name: SEDR
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anyio=4.9.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.17.1
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fqdn=1.5.1
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.21.3
  - libcxx=20.1.2
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pysocks=1.7.1
  - python=3.13.3
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - readline=8.2
  - referencing=0.36.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.24.0
  - send2trash=1.8.3
  - setuptools=78.1.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - pip:
      - anndata==0.11.4
      - array-api-compat==1.11.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - h5py==3.13.0
      - idna==3.10
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - legacy-api-wrap==1.4.1
      - llvmlite==0.44.0
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.2.4
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.2.1
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - requests==2.32.3
      - scanpy==1.11.1
      - scikit-learn==1.5.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - sedr==1.0.0
      - session-info2==0.1.2
      - statsmodels==0.14.4
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==2.4.0
